Fix watch task
openshift-eng/art-bot pull request #115
Opened 2023-03-20 10:49 UTC by locriandev

2023-03-20 14:17 UTC, thegreyd commented on artbotlib/help.py
> -* Watch `release_url|brew_url|prow_job_url`
I would like to keep the "Watch <url>" interface - it's intuitive and easy to remember
We can remove the ID regex

2023-03-20 14:20 UTC, thegreyd requested changes
Would like to keep "watch [url]" for brew.

2023-03-21 08:53 UTC, locriandev commented on artbotlib/help.py
> -* Watch `release_url|brew_url|prow_job_url`
done

2023-03-21 13:40 UTC, thegreyd commented
/lgtm

2023-03-21 13:41 UTC, merged