Update kerberos setup
openshift-eng/art-bot pull request #54
Opened 2022-12-18 03:55 UTC by ashwindasr

Updates in this PR:
- Added art-dash-server route as a constant to the repo https://github.com/openshift-eng/art-bot/commit/233baf2a35231bf83d3ee44a55adf65157ab5e0b
- Since we're already mounting the kerberos config file when we're starting the container, it's redundant for us to copy it in the Dockerfiles as well. If it's mounted, we'll have more control of the configuration and see changes reflected quickly. Also its better we mount the kerberos config to /etc/krb5.conf as its the first place that kerberos looks for the ticket. https://github.com/openshift-eng/art-bot/commit/0eb2a515b604f0680668ad0bde29f883a07e1e00
- Since art-bot development has been decoupled from slack, @.art-bot-dev is not longer used in slack. Hence there's no need to copy the settings.yaml in development anymore. UMB has also been removed. slack-app-token field added to `settings.yaml` as well. https://github.com/openshift-eng/art-bot/commit/75493e5a5a7ff224d7ab4334f6c31dd5bb767afe

2022-12-18 20:52 UTC, ashwindasr commented
Mounting to `/etc/krb5.conf` did not work in production dev. Keeping the config as is for now. Will create a new PR to update docs.

2022-12-19 17:33 UTC, locriandev requested changes

2022-12-19 17:33 UTC, locriandev commented on artbotlib/constants.py
> +ART_DASH_SERVER_ROUTE = "http://art-dash-server-art-build-dev.apps.ocp4.prod.psi.redhat.com"
```suggestion
ART_DASH_SERVER_ROUTE = "http://art-dash-server-art-build-dev.apps.ocp4.prod.psi.redhat.com/api/v1"
```

2022-12-19 17:36 UTC, locriandev commented
Generally lgtm, apart from the definition of `ART_DASH_SERVER_ROUTE` that should include `/api/v1` unless we think that the server base URL will be useful somewhere else.

What is `slack_app_token_file` needed for? How should we set that in production? (haven't found this anywhere)

2022-12-19 18:45 UTC, ashwindasr commented
> What is slack_app_token_file needed for? How should we set that in production? (haven't found this anywhere)


Its defined here: https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/k8s/ns/aos-art-web/secrets/art-bot-config. The `art-bot.py` has code that pulls it from the env.

2022-12-19 18:45 UTC, ashwindasr commented
> that should include /api/v1 unless we think that the server base URL will be useful somewhere else.

You're right. Will update.

2022-12-20 17:33 UTC, ashwindasr commented on artbotlib/constants.py
> +ART_DASH_SERVER_ROUTE = "http://art-dash-server-art-build-dev.apps.ocp4.prod.psi.redhat.com"
Fixed!

2022-12-22 16:15 UTC, locriandev commented
/lgtm

2022-12-22 16:15 UTC, locriandev approved these changes

2022-12-22 16:54 UTC, merged