Poll for a Prow job state
openshift-eng/art-bot pull request #59
Opened 2023-01-10 14:26 UTC by locriandev

Ref. https://issues.redhat.com/browse/ART-5685

2023-01-11 17:58 UTC, ashwindasr requested changes

2023-01-11 17:58 UTC, ashwindasr commented on artbotlib/prow.py
> +            return
It might be a good idea to ping to the user if the pod is restarted while this loop is running right? Like for nightly/release color.

2023-01-11 18:07 UTC, ashwindasr commented on artbotlib/regex_mapping.py
> +            "regex": rf"^Alert ?(if|when|on)? first prow job in(?P<job_paths>(( )*{PROW_BASE_URL}/view/gs/\S*)*) succeedes$",
Also a typo `succeeds`, should be `succeeds` right. Here and other places as well

2023-01-12 08:51 UTC, locriandev commented on artbotlib/regex_mapping.py
> +            "regex": rf"^Alert ?(if|when|on)? first prow job in(?P<job_paths>(( )*{PROW_BASE_URL}/view/gs/\S*)*) succeedes$",
right, fixed

2023-01-12 17:25 UTC, locriandev commented on artbotlib/prow.py
> +            return
Done in https://github.com/openshift-eng/art-bot/pull/59/commits/57757ebe5e7b207a1894514aebfe5ed771fb9eb1

2023-01-12 17:25 UTC, merged