Refactor image pipeline code to use API endpoint
openshift-eng/art-bot pull request #67
Opened 2023-01-31 13:21 UTC by ashwindasr

The image pipeline code was migrated to the back-end API server. Refactor the code to use the data from the API server. Due to some complications with the regex, keeping multiple functions for each starting point eg: `github`, `cdn` etc. Will make the change in a separate PR.

2023-02-01 10:46 UTC, locriandev requested changes

2023-02-01 10:46 UTC, locriandev commented on artbotlib/pipeline_image_names.py
> +        if distgit['brew']['bundle_component'] != "None":
Wouldn't it be better to have art-dash response with `null` instead?
Then we could check it simply by `if distgit['brew']['bundle_component']:`

2023-02-01 10:46 UTC, locriandev commented on artbotlib/pipeline_image_names.py
> +        if len(cdns) > 1:
```suggestion
        if cdns:
```

2023-02-01 10:46 UTC, locriandev commented on artbotlib/pipeline_image_names.py
> +def process_data(response_data):
```suggestion
def process_data(response_data: dict):
```

2023-02-01 10:46 UTC, locriandev commented on artbotlib/pipeline_image_names.py
> +            raise Exception(response.json().get("payload"))
If  `response.status_code != 200`, `response.json()` will fail. I'd suggest rewriting this whole block to handle the different issues we might forsee:
- `status code != 200`: something's wrong on art-dash server
- `"status" != "success"`: the server responded with a failure state
- `"payload" not in response.json()`: unexpected payload

E.g.:

```
if response.status_code != 200:
    so.say('server error...')
    return

try:
    json_data = response.json()
except:
    so.say('unexpected payload')
    return

if json_data.get("status") != "success":
   so.say('failure...')
   return

try:
    payload = process_data(json_data["payload"])
    so.say(payload)
except KeyError:
    so.say('...')
```

2023-02-01 10:46 UTC, locriandev commented on artbotlib/pipeline_image_util.py
> +        return tag[4:] if tag.startswith("ose-") else tag  # remove 'ose-' if present
```suggestion
        return tag[4:] if tag.startswith("ose-") else tag  # remove 'ose-' if present
    return None
```

2023-02-02 15:24 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +        if len(cdns) > 1:
This will return true if list contains any element right? I was trying to check if the list has 2 or more elements

2023-02-02 15:32 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +            raise Exception(response.json().get("payload"))
If response.status_code != 200, then python wont check anything after the subsequent `and` right?

2023-02-02 15:46 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +        if distgit['brew']['bundle_component'] != "None":
Fixed in https://github.com/openshift-eng/art-bot/pull/72

2023-02-02 15:46 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +def process_data(response_data):
Fixed in https://github.com/openshift-eng/art-bot/pull/72

2023-02-02 15:46 UTC, ashwindasr commented on artbotlib/pipeline_image_names.py
> +            raise Exception(response.json().get("payload"))
Fixed in https://github.com/openshift-eng/art-bot/pull/72

2023-02-02 15:50 UTC, ashwindasr commented on artbotlib/pipeline_image_util.py
> +        return tag[4:] if tag.startswith("ose-") else tag  # remove 'ose-' if present
Fixed in https://github.com/openshift-eng/art-bot/pull/72

2023-02-02 16:21 UTC, locriandev commented on artbotlib/pipeline_image_names.py
> +        if len(cdns) > 1:
Right :) my bad

2023-02-02 16:57 UTC, ashwindasr commented
Tested in `art-build-dev` Merging.

2023-02-02 16:58 UTC, merged