add elliott go cli
openshift-eng/art-bot pull request #99
Opened 2023-02-21 08:01 UTC by Ximinhan

accordinng to https://groups.google.com/a/redhat.com/g/aos-team-art/c/JEIYQgTGhQE
I would like to add elliott go cli for advisory parameter

2023-02-21 17:12 UTC, ashwindasr requested changes

2023-02-21 17:12 UTC, ashwindasr commented on artbotlib/elliott.py
> +        so.snippet(payload=stdout, intro=f"Go version for advisory {advisory}:", filename='go_advisory_output.txt')
It should be `advisory_id` instead of `advisory`, since thats the name of the group defined in the regex `^(go|golang) version (for|of) advisory (?P<advisory_id>\d+)$`

2023-02-21 17:13 UTC, ashwindasr commented
Can you tell me a command that works so that I can test it out? I tried against some of the advisories in 4.12.3 but didn't work.

2023-02-23 07:56 UTC, Ximinhan commented
@ashwindasr parameter updated, it should looks like
```
$ python3 ./elliott go -a 104601
Following nvrs are built with openshift-golang-builder-container-v1.16.12-202208011952.el8.g58dffad:
ose-etcd-container-v4.12.0-202212121125.p0.g89a451c.assembly.stream
Following nvrs are built with openshift-golang-builder-container-v1.19.4-202301042245.el8.g1832cfe:
atomic-openshift-cluster-autoscaler-container-v4.12.0-202301042354.p0.g6ab8e62.assembly.stream
baremetal-machine-controller-container-v4.12.0-202301042354.p0.g63dcaf1.assembly.stream
cluster-etcd-operator-container-v4.12.0-202301042354.p0.gf24e5ab.assembly.stream
cluster-monitoring-operator-container-v4.12.0-202301050335.p0.gee31d1d.assembly.stream
cluster-network-operator-container-v4.12.0-202301042354.p0.g9eafe23.assembly.stream
```

2023-02-23 08:06 UTC, Ximinhan commented
> Can you tell me a command that works so that I can test it out? I tried against some of the advisories in 4.12.3 but didn't work.

for rpm advisory it should looks like
```
$ python3 ./elliott go -a 109778
Following nvrs are built with 1.19.4-2.module+el8.8.0+17709+252fe516:
buildah-1.23.4-4.rhaos4.12.el8
conmon-2.1.2-3.rhaos4.12.el8
containernetworking-plugins-1.0.1-6.rhaos4.12.el8
cri-o-1.25.2-6.rhaos4.12.git3c4e50c.el8
openshift-clients-4.12.0-202301312133.p0.gb05f7d4.assembly.stream.el8
runc-1.1.4-2.rhaos4.12.el8
skopeo-1.9.4-2.rhaos4.12.el8
```

2023-02-23 08:08 UTC, Ximinhan commented
> Can you tell me a command that works so that I can test it out? I tried against some of the advisories in 4.12.3 but didn't work.

for rpm advisory it should looks like
```
$ python3 ./elliott go -a 109778
Following nvrs are built with 1.19.4-2.module+el8.8.0+17709+252fe516:
buildah-1.23.4-4.rhaos4.12.el8
conmon-2.1.2-3.rhaos4.12.el8
containernetworking-plugins-1.0.1-6.rhaos4.12.el8
cri-o-1.25.2-6.rhaos4.12.git3c4e50c.el8
openshift-clients-4.12.0-202301312133.p0.gb05f7d4.assembly.stream.el8
runc-1.1.4-2.rhaos4.12.el8
skopeo-1.9.4-2.rhaos4.12.el8
```

2023-02-23 14:52 UTC, ashwindasr requested changes

2023-02-23 14:52 UTC, ashwindasr commented on artbotlib/elliott.py
> +        util.please_notify_art_team_of_error(so, stderr)
Can you change this to 

>     if not stdout:
>         so.say("Invalid advisory. Try again.")

2023-02-23 15:00 UTC, ashwindasr approved these changes

2023-02-23 15:03 UTC, merged